name: Alert

on:
  workflow_dispatch:

jobs:
  alert:
    name: Alert
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: auth-gcloud
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Install private dependencies
        run: pip install -vv warn-bot --no-input
        shell: bash
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth-gcloud.outputs.credentials_file_path }}

      - name: Send alert
        run: pipenv run warn-bot --help