name: Alert

on:
  workflow_dispatch:

jobs:
  transform:
    name: Transform
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install public dependencies
        uses: ./.github/actions/install

      - id: auth-gcloud
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/990992937017/locations/global/workloadIdentityPools/warn-pool/providers/warn-provider
          service_account: warn-service-account@big-local-news-267923.iam.gserviceaccount.com
          create_credentials_file: true

      - name: Install private dependencies
        run: pipenv install --index-url https://us-west2-python.pkg.dev/big-local-news-267923/warn-bot/ warn-bot
        shell: bash
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth-gcloud.outputs.credentials_file_path }}

      - name: Send alert
        run: pipenv run warn-bot --help