name: Extract, transform and load

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  extract:
    strategy:
      fail-fast: false
      matrix:
        source:
          [
            al,
            ak,
            az,
            ca,
            ct,
            dc,
            de,
            fl,
            ga,
            ia,
            id,
            il,
            in,
            ks,
            ky,
            la,
            md,
            me,
            mi,
            mo,
            mt,
            ne,
            nj,
            nm,
            ny,
            oh,
            ok,
            or,
            ri,
            sc,
            sd,
            tn,
            tx,
            ut,
            va,
            vt,
            wa,
            wi,
          ]
    name: Extract
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Extract
        uses: ./.github/actions/extract
        with:
          source: ${{ matrix.source }}
          bln-api-key: ${{ secrets.BLN_API_TOKEN }}
          bln-project-id: ${{ secrets.BLN_PROJECT_ID }}

      - name: Fail alert
        id: slack
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "🚨 WARN Act Notice ETL scrape for `${{ matrix.source }}` failed at https://github.com/biglocalnews/warn-github-flow/actions"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  transform:
    name: Transform
    runs-on: ubuntu-latest
    needs: [extract]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Transform
        uses: ./.github/actions/transform
        with:
          bln-api-key: ${{ secrets.BLN_API_TOKEN }}
          bln-project-id: ${{ secrets.BLN_PROJECT_ID }}

      - name: Fail alert
        id: slack
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "🚨 WARN Act Notice ETL transformation failed at https://github.com/biglocalnews/warn-github-flow/actions"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  slack-success:
    name: Send Slack success alert
    runs-on: ubuntu-latest
    needs: [transform]
    steps:
      - name: Post
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "👍 WARN Act Notice ETL finished at https://github.com/biglocalnews/warn-github-flow/actions"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
