name: Extract, transform and load

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  extract:
    strategy:
      fail-fast: false
      matrix:
        source:
          [
            al,
            ak,
            az,
            ca,
            ct,
            dc,
            de,
            fl,
            ga,
            ia,
            id,
            il,
            in,
            ks,
            ky,
            la,
            md,
            me,
            mi,
            mo,
            mt,
            ne,
            nj,
            nm,
            ny,
            oh,
            ok,
            or,
            ri,
            sc,
            sd,
            tn,
            tx,
            ut,
            va,
            vt,
            wa,
            wi,
          ]
    name: Extract
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract
        uses: ./.github/actions/extract
        with:
          source: ${{ matrix.source }}
          bln-api-key: ${{ secrets.BLN_API_TOKEN }}
          bln-project-id: ${{ secrets.BLN_PROJECT_ID }}

      - name: Fail alert
        id: slack
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "🚨 WARN Act Notice ETL scrape for `${{ matrix.source }}` failed at https://github.com/biglocalnews/warn-github-flow/actions"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  transform:
    name: Transform
    runs-on: ubuntu-latest
    needs: [extract]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: install-pipenv
        name: Install pipenv
        run: pipx install pipenv

      - id: install-python
        name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - id: install-python-dependencies
        name: Install Python dependencies
        run: pipenv install --dev

      - id: checkout
        name: Checkout branch
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git config pull.rebase false
            git checkout transformer
            git pull origin main

      - name: Download files
        run: pipenv run warn-transformer download -l DEBUG
        env:
            BLN_API_TOKEN: ${{ secrets.BLN_API_TOKEN }}
            WARN_TRANSFORMER_OUTPUT_DIR: ./data/warn-transformer/

      - name: Consolidate files
        run: pipenv run warn-transformer consolidate -l DEBUG
        env:
            WARN_TRANSFORMER_OUTPUT_DIR: ./data/warn-transformer/

      - name: Integrate files
        run: pipenv run warn-transformer integrate -l DEBUG
        env:
            WARN_TRANSFORMER_OUTPUT_DIR: ./data/warn-transformer/

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update transformer
          branch: transformer
          skip_checkout: true
          push_options: '--force'
          file_pattern: ./data/warn-transformer/*

      - name: Upload file to biglocalnews.org
        uses: biglocalnews/upload-files@v1
        with:
          api-key: ${{ secrets.BLN_API_TOKEN }}
          project-id: ${{ secrets.BLN_PROJECT_ID }}
          path: ./data/warn-transformer/processed/

      - name: Fail alert
        id: slack
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "🚨 WARN Act Notice ETL transformation failed at https://github.com/biglocalnews/warn-github-flow/actions"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  slack-success:
    name: Send Slack success alert
    runs-on: ubuntu-latest
    needs: [transform]
    steps:
      - name: Post
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "👍 WARN Act Notice ETL finished at https://github.com/biglocalnews/warn-github-flow/actions"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
