name: Transform

on:
  workflow_dispatch:

jobs:
  transform:
    name: Transform
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Download files
        run: pipenv run warn-transformer download -l DEBUG
        env:
            BLN_API_TOKEN: ${{ secrets.BLN_API_TOKEN }}
            WARN_TRANSFORMER_OUTPUT_DIR: ./data/warn-transformer/
        shell: bash

      - name: Consolidate files
        run: pipenv run warn-transformer consolidate -l DEBUG
        env:
            WARN_TRANSFORMER_OUTPUT_DIR: ./data/warn-transformer/
        shell: bash

      - name: Transform
        uses: ./.github/actions/transform
        with:
          bln-api-key: ${{ secrets.BLN_API_TOKEN }}
          bln-project-id: ${{ secrets.BLN_PROJECT_ID }}
